# Generated by Django 5.1.7 on 2026-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
